dedipanel_teamspeak_index:
    pattern: /
    defaults:
        _controller: dedipanel.controller.teamspeak:indexAction
        _sylius:
            paginate: false
            criteria:
                groups: @dedipanel.resolver.user_group:getAccessibleGroupsIdOrEmpty

dedipanel_teamspeak_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.teamspeak:createAction
        _sylius:
            form: dedipanel_teamspeak_add
            redirect:
                route: dedipanel_teamspeak_instance_index
                parameters:
                    serverId: resource.id

dedipanel_teamspeak_update:
    pattern: /{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.teamspeak:updateAction
        _sylius:
            form: dedipanel_teamspeak_edit
            redirect: dedipanel_teamspeak_index

dedipanel_teamspeak_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: dedipanel.controller.teamspeak:deleteAction
        # template: DPTeamspeakServerBundle:TeamspeakServer:delete.html.twig

dedipanel_teamspeak_change_state:
     pattern: /{id}/change-state
     methods: [GET]
     defaults:
         _controller: dedipanel.controller.teamspeak:changeStateAction
