# Copyright (C) 2010-2013 Kerouanton Albin, Smedts Jérôme
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

dedipanel_steam_index:
    pattern: /
    defaults:
        _controller: dedipanel.controller.steam:indexAction
        _sylius:
            paginate: false
            criteria:
                groups: @dedipanel.resolver.user_group:getAccessibleGroupsId

dedipanel_steam_show:
    pattern: /{id}/show
    defaults:
        _controller: dedipanel.controller.steam:showAction
        _sylius:
            paginate: false

dedipanel_steam_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.steam:createAction
        _sylius:
            redirect: dedipanel_steam_index

dedipanel_steam_update:
    pattern: /{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.steam:updateAction

dedipanel_steam_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: dedipanel.controller.steam:deleteAction
        template: DPSteamServerBundle:SteamServer:delete.html.twig

dedipanel_steam_install:
    pattern: /{id}/install
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.steam:installProgressAction

dedipanel_steam_regen:
    pattern: /{id}/regen
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.steam:regenAction

dedipanel_steam_logs:
    pattern: /{id}/logs
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.steam:logsAction

dedipanel_steam_change_state:
    pattern: /{id}/change-state
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.steam:changeStateAction

dedipanel_steam_rcon_json:
    pattern: /{id}/rcon
    methods: [GET, POST]
    requirements:
        _format: json
    defaults:
        _format: json
        _controller: dedipanel.controller.steam:rconAction

dedipanel_steam_rcon:
    pattern: /{id}/rcon
    methods: [GET, POST]
    requirements:
        _format: html
    defaults:
        _format: html
        _controller: dedipanel.controller.steam:rconAction

dedipanel_steam_plugin_install:
    pattern: /{id}/plugin/{plugin}/install
    methods: [GET]
    defaults:
        action: install
        _controller: dedipanel.controller.steam:pluginAction

dedipanel_steam_plugin_uninstall:
    pattern: /{id}/plugin/{plugin}/uninstall
    methods: [GET]
    defaults:
        action: uninstall
        _controller: dedipanel.controller.steam:pluginAction

dedipanel_steam_plugin:
    pattern: /{id}/plugin
    methods: [GET]
    defaults:
        _controller: dedipanel.controller.steam:showAction
        _sylius:
            template: DPSteamServerBundle:SteamServer:plugin_show.html.twig

DPSteamServerBundle_FTP:
    resource: "@DPSteamServerBundle/Resources/config/routing/ftp.yml"
    prefix: /{id}/ftp/
    requirements: {id: \d+}
