parameters:
#    dp_steam_server.example.class: DP\GameServer\SteamServerBundle\Example

services:
#    dp_steam_server.example:
#        class: %dp_steam_server.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
