# This file is part of Dedipanel project
#
# (c) 2010-2015 Dedipanel <http://www.dedicated-panel.net>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    packet.factory.steam.query:
        class: DP\GameServer\SteamServerBundle\Service\PacketFactory\SteamQueryPacketFactory
    packet.factory.rcon.goldsrc:
        class: DP\GameServer\SteamServerBundle\Service\PacketFactory\GoldSrcRconPacketFactory
    packet.factory.rcon.source:
        class: DP\GameServer\SteamServerBundle\Service\PacketFactory\SourceRconPacketFactory
    
    query.steam:
        class: DP\GameServer\SteamServerBundle\Service\Query
        arguments: [ @service_container ]
    
    rcon.steam:
        class: DP\GameServer\SteamServerBundle\Service\RconService
        arguments: [ @service_container ]
    
    steam.listener.configModifier:
        class: DP\GameServer\SteamServerBundle\Listener\ConfigModifier
        arguments: [ @service_container ]
        calls:
            - [ setServiceContainer, [ @service_container ] ]
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
    
    dedipanel.steam.form.add:
        class: DP\GameServer\SteamServerBundle\Form\SteamServerType
        tags:
            - { name: form.type, alias: dedipanel_steam }
