# (c) 2010-2014 Dedipanel <http://www.dedicated-panel.net>
# 
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

imports:
    - { resource: config_prod.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_installer.yml" }
