imports:
    - { resource: config_prod.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_installer.yml" }

doctrine_migrations:
    name: DediPanel Migrations
    table_name: migration_versions
    namespace: DP\Core\DistributionBundle\Migrations
    dir_name: %kernel.root_dir%/../src/DP/Core/DistributionBundle/Migrations
