imports:
    - { resource: config.yml }

framework:
    test: ~
    router:   { resource: "%kernel.root_dir%/config/routing_installer.yml" }
    profiler: { only_exceptions: false }

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        dbname: %database_name%_test

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
            channels: !phpseclib

doctrine_migrations:
    name: DediPanel Migrations
    table_name: migration_versions
    namespace: DP\Core\DistributionBundle\Migrations
    dir_name: %kernel.root_dir%/../src/DP/Core/DistributionBundle/Migrations
