security:   
    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN:       [ROLE_USER, ROLE_DP_ADMIN, ROLE_DP_ADMIN_MACHINE_ADMIN]
        ROLE_DP_ADMIN_MACHINE_ADMIN:  [ROLE_DP_ADMIN_MACHINE_SHOW, ROLE_DP_ADMIN_MACHINE_CREATE, ROLE_DP_ADMIN_MACHINE_UPDATE, ROLE_DP_ADMIN_MACHINE_DELETE]
        ROLE_DP_ADMIN_MACHINE_SHOW:   [ROLE_DP_ADMIN_MACHINE_SHOW]
        ROLE_DP_ADMIN_MACHINE_CREATE: [ROLE_DP_ADMIN_MACHINE_SHOW, ROLE_DP_ADMIN_MACHINE_CREATE]
        ROLE_DP_ADMIN_MACHINE_UPDATE: [ROLE_DP_ADMIN_MACHINE_SHOW, ROLE_DP_ADMIN_MACHINE_UPDATE]
        ROLE_DP_ADMIN_MACHINE_DELETE: [ROLE_DP_ADMIN_MACHINE_SHOW, ROLE_DP_ADMIN_MACHINE_DELETE]
