_welcome:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: dedipanel_installer
        permanent: true

installer:
    resource: "@DPDistributionBundle/Resources/config/routing.yml"
    prefix:   /installer/
