# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

DPUserBundle:
    resource: "@DPUserBundle/Resources/config/routing.yml"
    prefix: /