DPSteamServerBundle:
    resource: "@DPSteamServerBundle/Resources/config/routing.yml"
    prefix:   /steam/

DPGameBundle:
    resource: "@DPGameBundle/Resources/config/routing.yml"
    prefix:   /

DPMachineBundle:
    resource: "@DPMachineBundle/Resources/config/routing.yml"
    prefix:   /machine/

ApplicationSonataUserBundle:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing.yml"
    prefix: /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

_sonata_admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    type: sonata_admin
    prefix: /admin

sonata_user_impersonating:
    pattern: /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal