# (c) 2010-2014 Dedipanel <http://www.dedicated-panel.net>
# 
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

DPUserBundle:
    resource: "@DPUserBundle/Resources/config/routing.yml"
    prefix:   /admin
    
DPGameBundle:
    resource: "@DPGameBundle/Resources/config/routing.yml"
    prefix:   /admin

DPGameServerBundle:
    resource: "@DPGameServerBundle/Resources/config/routing.yml"
    prefix:   /game

DPMachineBundle:
    resource: "@DPMachineBundle/Resources/config/routing.yml"
    prefix:   /machine

DPCoreBundle:
    resource: "@DPCoreBundle/Resources/config/routing.yml"
    prefix:   /configure/

DPVoipServerBundle:
    resource: "@DPVoipServerBundle/Resources/config/routing.yml"
    prefix:   /voip

# FOSUserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

_welcome:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: '::layout.html.twig'
