_main:
    resource: routing.yml

installer:
    resource: "@DPDistributionBundle/Resources/config/routing.yml"
    prefix:   /installer/

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler
