# (c) 2010-2014 Dedipanel <http://www.dedicated-panel.net>
# 
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

imports:
    - { resource: roles.yml }

security:
    access_decision_manager:
        strategy: unanimous
    
    encoders:
        "FOS\UserBundle\Model\UserInterface": sha512
    
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    
    firewalls:
        installer:
            pattern: ^/installer
            anonymous: true
        
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        login:
            pattern: ^/(login$|register|resetting)
            anonymous: true
        
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            anonymous: false
            logout: true
    
    access_control:
        - { path: ^/installer, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY } 
