# (c) 2011-2014 Dedipanel <http://www.dedicated-panel.net>
# 
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

dedipanel_plugin_index:
    pattern: /
    defaults:
        _controller: dedipanel.controller.plugin:indexAction

dedipanel_plugin_show:
    pattern: /{id}/show
    defaults:
        _controller: dedipanel.controller.plugin:showAction

dedipanel_plugin_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.plugin:createAction

dedipanel_plugin_update:
    pattern: /{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.plugin:updateAction

dedipanel_plugin_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: dedipanel.controller.plugin:deleteAction
        template: DPGameBundle:Plugin:delete.html.twig
