# (c) 2010-2014 Dedipanel <http://www.dedicated-panel.net>
# 
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

steam_hltv_show:
    pattern: /
    defaults: { _controller: "DPSteamServerBundle:Hltv:show" }

steam_hltv_start:
    pattern: /start
    defaults: { _controller: "DPSteamServerBundle:Hltv:start" }
    requirements:
        _method: 'post'

steam_hltv_stop:
    pattern: /stop
    defaults: { _controller: "DPSteamServerBundle:Hltv:stop" }
