steam_plugins_show:
    pattern: /
    defaults: { _controller: "DPSteamServerBundle:Plugins:showServer" }

steam_plugins_install:
    pattern: /install/{plugin}
    defaults: { _controller: "DPSteamServerBundle:Plugins:install" }
#    requirements:
#        plugin: metamod|amx|amxx|metamodSource|sourceMod|eventScripts

steam_plugins_uninstall:
    pattern: /uninstall/{plugin}
    defaults: { _controller: "DPSteamServerBundle:Plugins:uninstall" }
#    requirements:
#        plugin: metamod|amx|amxx|metamodSource|sourceMod|eventScripts