steam_plugins_show:
    pattern: /
    defaults: { _controller: "DPSteamServerBundle:Plugins:showServer" }

steam_plugins_install:
    pattern: /{plugin}/install/
    defaults: { _controller: "DPSteamServerBundle:Plugins:install" }
    requirements: {plugin: \d+}

steam_plugins_uninstall:
    pattern: /{plugin}/uninstall/
    defaults: { _controller: "DPSteamServerBundle:Plugins:uninstall" }
    requirements: {plugin: \d+}