# This file is part of Dedipanel project
#
# (c) 2010-2014 Dedipanel <http://www.dedicated-panel.net>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    dedipanel.security.form.roles_type:
        class: DP\Core\UserBundle\Form\RolesType
        arguments: [ @dedipanel.security.form.roles_type.subscriber, %security.role_hierarchy.roles%, @security.context ]
        tags:
            - { name: form.type, alias: dp_security_roles }
    
    dedipanel.security.form.roles_type.subscriber:
        class: DP\Core\UserBundle\EventListener\RolesTypeSubscriber
        arguments: [ @security.role_hierarchy, %security.role_hierarchy.roles% ]
