# This file is part of Dedipanel project
#
# (c) 2010-2015 Dedipanel <http://www.dedicated-panel.net>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    dp_menu.factory:
        class: DP\Core\UserBundle\Menu\Factory\MenuFactory
        arguments: [ "@router" ]
    
    app_user.menu_builder:
        class: DP\Core\UserBundle\Menu\Builder\MenuBuilder
        arguments: [ @dp_menu.factory, @security.context ]
    
    app_user.menu.main:
        class: DP\Core\Menu\MenuItem
        factory_service: app_user.menu_builder
        factory_method: createMainMenu
        arguments: [ "@request" ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }