services:
    app_user.update_watcher.service:
        class: DP\Core\UserBundle\Service\UpdateWatcherService
        arguments: [0.4]

    app_user.update_watcher.extension:
        class: DP\Core\UserBundle\Extension\UpdateWatcherExtension
        arguments: [@app_user.update_watcher.service]
        tags:
            - { name: twig.extension }
