# This file is part of Dedipanel project
#
# (c) 2010-2014 Dedipanel <http://www.dedicated-panel.net>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

dedipanel_installer:
    pattern:  /
    defaults: { _controller: DPDistributionBundle:Configurator:index }

dedipanel_installer_check:
    pattern: /{type}/check
    defaults: { _controller: DPDistributionBundle:Configurator:check }
    requirements:
        type: install|update

dedipanel_installer_step:
    pattern: /{type}/{step}
    defaults: { _controller: DPDistributionBundle:Configurator:step }
    requirements: 
        step: \d
        type: install|update

dedipanel_installer_final_step:
    pattern: /{type}/final
    defaults: { _controller: DPDistributionBundle:Configurator:final }
    requirements:
        type: install|update

dedipanel_installer_rewrite_front_script:
    pattern: /rewrite
    defaults: { _controller: DPDistributionBundle:Configurator:rewriteFrontScript }
