# Copyright (C) 2010-2013 Kerouanton Albin, Smedts Jérôme

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

dedipanel_installer:
    pattern:  /
    defaults: { _controller: DPDistributionBundle:Configurator:index }

dedipanel_installer_check:
    pattern: /install/check
    defaults: { _controller: DPDistributionBundle:Configurator:check }

dedipanel_installer_step:
    pattern: /{type}/{step}
    defaults: { _controller: DPDistributionBundle:Configurator:step }
    requirements: 
      step: \d
      type: install|update

installer_final:
    pattern: /{type}/final
    defaults: { _controller: DPDistributionBundle:Configurator:final }
    requirements:
        type: install|update

dedipanel_installer_rewrite_front_script:
    pattern: /rewrite
    defaults: { _controller: DPDistributionBundle:Configurator:rewriteFrontScript }
