# This file is part of Dedipanel project
#
# (c) 2010-2015 Dedipanel <http://www.dedicated-panel.net>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    dp.webinstaller:
        class: "DP\Core\DistributionBundle\Configurator\Configurator"
        arguments: [ %kernel.root_dir% ]

    dedipanel.installer.security_voter:
        class: DP\Core\DistributionBundle\Security\InstallerVoter
        arguments: [ @service_container, "%kernel.root_dir%/../installer_whitelist.txt" ]
        public: false
        tags:
            - { name: security.voter }
