DPMinecraftServerBundle:
    resource: "@DPMinecraftServerBundle/Resources/config/routing/minecraftServer.yml"
    prefix: /

DPMinecraftServerBundle_Plugins:
    resource: "@DPMinecraftServerBundle/Resources/config/routing/plugins.yml"
    prefix: /{id}/plugins/
    requirements: {id: \d+}

DPMinecraftServerBundle_Rcon:
    resource: "@DPMinecraftServerBundle/Resources/config/routing/rcon.yml"
    prefix: /{id}/rcon/
    requirements: {id: \d+}

DPMinecraftServerBundle_FTP:
    resource: "@DPMinecraftServerBundle/Resources/config/routing/ftp.yml"
    prefix: /{id}/ftp/
    requirements: {id: \d+}