# (c) 2010-2014 Dedipanel <http://www.dedicated-panel.net>
# 
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    packet.factory.minecraft.query:
        class: DP\GameServer\MinecraftServerBundle\Service\MinecraftQueryPacketFactory
    
    query.minecraft:
        class: DP\GameServer\MinecraftServerBundle\Service\Query
        arguments: [ @service_container ]
        
    rcon.minecraft:
        class: DP\GameServer\MinecraftServerBundle\Service\RconService
        arguments: [ @service_container ]
    
    minecraft.listener.configModifier:
        class: DP\GameServer\MinecraftServerBundle\Listener\ConfigModifier
        arguments: [ @service_container ]
        calls:
            - [ setServiceContainer, [ @service_container ] ]
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
    
    dedipanel.minecraft.form:
        class: DP\GameServer\MinecraftServerBundle\Form\MinecraftServerType
        tags:
            - { name: form.type, alias: dedipanel_minecraft }
