DPGameBundle_Game:
    resource: "@DPGameBundle/Resources/config/routing/game.yml"
    prefix:   /game/
    
DPGameBundle_plugin:
    resource: "@DPGameBundle/Resources/config/routing/plugin.yml"
    prefix:   /plugin/
