# This file is part of Dedipanel project
#
# (c) 2010-2015 Dedipanel <http://www.dedicated-panel.net>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

services:
    dedipanel.game.form.add_edit:
        class: DP\Core\GameBundle\Form\GameType
        tags:
            - { name: form.type, alias: dedipanel_game }
    
    dedipanel.plugin.form.add_edit:
        class: DP\Core\GameBundle\Form\PluginType
        tags:
            - { name: form.type, alias: dedipanel_plugin }
