# (c) 2010-2014 Dedipanel <http://www.dedicated-panel.net>
# 
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

dedipanel_group_index:
    pattern: /
    defaults:
        _controller: dedipanel.controller.group:indexAction
        _sylius:
            role: ROLE_DP_ADMIN_GROUP_ADMIN

dedipanel_group_show:
    pattern: /{id}/show
    defaults:
        _controller: dedipanel.controller.group:showAction
        _sylius:
            role: ROLE_DP_ADMIN_GROUP_ADMIN

dedipanel_group_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.group:createAction
        _sylius:
            role: ROLE_DP_ADMIN_GROUP_ADMIN

dedipanel_group_update:
    pattern: /{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.group:updateAction
        _sylius:
            role: ROLE_DP_ADMIN_GROUP_ADMIN

dedipanel_group_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: dedipanel.controller.group:deleteAction
        template: DPCoreUserBundle:Group:delete.html.twig
        _sylius:
            role: ROLE_DP_ADMIN_GROUP_ADMIN
