group_admin:
    pattern:  /
    defaults: { _controller: "DPAdminUserBundle:Group:index" }

group_admin_new:
    pattern:  /new
    defaults: { _controller: "DPAdminUserBundle:Group:new" }

group_admin_create:
    pattern:  /create
    defaults: { _controller: "DPAdminUserBundle:Group:create" }
    requirements: { _method: post }

group_admin_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "DPAdminUserBundle:Group:edit" }

group_admin_update:
    pattern:  /{id}/update
    defaults: { _controller: "DPAdminUserBundle:Group:update" }
    requirements: { _method: post|put }
    
group_admin_batch_delete:
    pattern:  /batch/delete
    defaults: { _controller: "DPAdminUserBundle:Group:batchDelete" }
    requirements: { _method: post|delete }

group_admin_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "DPAdminUserBundle:Group:delete" }
    requirements: { _method: post|delete }
