# This file is part of Dedipanel project
#
# (c) 2010-2015 Dedipanel <http://www.dedicated-panel.net>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

dedipanel_minecraft_ftp_show:
    pattern: /show/{path}
    requirements:
        path: .*
    defaults:
        path: /
        type: directory
        _controller: dedipanel.minecraft.controller.ftp:showAction
        _sylius:
            role: ROLE_DP_GAME_MINECRAFT_FTP

dedipanel_minecraft_ftp_create:
    pattern: /{type}/new/{path}
    methods: [GET, POST]
    requirements:
        type: file|directory
        path: .*
    defaults:
        _controller: dedipanel.minecraft.controller.ftp:createAction
        _sylius:
            form: dedipanel_game_ftp_add
            role: ROLE_DP_GAME_MINECRAFT_FTP

dedipanel_minecraft_ftp_update:
    pattern: /edit/{path}
    methods: [GET, POST]
    requirements:
        path: .+
    defaults:
        _controller: dedipanel.minecraft.controller.ftp:updateAction
        _sylius:
            form: dedipanel_game_ftp_edit
            role: ROLE_DP_GAME_MINECRAFT_FTP

dedipanel_minecraft_ftp_delete:
    pattern: /delete/{path}
    methods: [DELETE]
    requirements:
        path: .+
    defaults:
        template: DPMinecraftServerBundle:FTP:delete.html.twig
        _controller: dedipanel.minecraft.controller.ftp:deleteAction
        _sylius:
            role: ROLE_DP_GAME_MINECRAFT_FTP
