# Copyright (C) 2010-2013 Kerouanton Albin, Smedts Jérôme
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

minecraft:
    pattern:  /
    defaults: { _controller: "DPMinecraftServerBundle:MinecraftServer:index" }

minecraft_show:
    pattern:  /{id}/show
    defaults: { _controller: "DPMinecraftServerBundle:MinecraftServer:show" }

minecraft_new:
    pattern:  /new
    defaults: { _controller: "DPMinecraftServerBundle:MinecraftServer:new" }

minecraft_create:
    pattern:  /create
    defaults: { _controller: "DPMinecraftServerBundle:MinecraftServer:create" }
    requirements: { _method: post }

minecraft_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "DPMinecraftServerBundle:MinecraftServer:edit" }

minecraft_update:
    pattern:  /{id}/update
    defaults: { _controller: "DPMinecraftServerBundle:MinecraftServer:update" }
    requirements: { _method: post }

minecraft_delete:
    pattern:  /{id}/delete/{fromMachine}
    defaults: { _controller: "DPMinecraftServerBundle:MinecraftServer:delete", fromMachine: false }
    requirements: { _method: post }

minecraft_install:
    pattern:  /{id}/install
    defaults: { _controller : "DPMinecraftServerBundle:MinecraftServer:install" }

minecraft_changeState:
    pattern:  /{id}/{state}
    defaults: { _controller: "DPMinecraftServerBundle:MinecraftServer:changeState" }
    requirements: { state: "start|stop|restart" }

minecraft_regen:
    pattern: /{id}/regen
    defaults: { _controller: "DPMinecraftServerBundle:MinecraftServer:regen" }

minecraft_screen_log:
    pattern: /{id}/log
    defaults: { _controller: "DPMinecraftServerBundle:MinecraftServer:showLog" }
