User:
  tableName: users
  columns:
    id: {type: integer, primary: true, autoincrement: true}
    pseudo: {type: string(15), notnull: true}
    email: {type: string(40), email: true, notnull: true}
    mdp: {type: string(40), notnull: true}
    lang: {type: string(6), notnull: true, default: fr}
    
UserGroup:
  tableName: usersgroups
  columns:
    user_id: {type: integer}
    group_id: {type: integer}
  relations:
    Group: { foreignAlias: GroupUsers, local: group_id, foreign: id }
    User:  { foreignAlias: GroupUsers, local: user_id, foreign: id  }

Vm:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    ip:
      type: string(15)
      ip: true
      notnull: true
    port: {type: int(5), notnull: true}
    user: {type: string(16), notnull: true}
    keyfile: {type: string(23), notnull: true}

GroupVm:
  tableName: groupvms
  columns:
    group_id: {type: integer, notnull: true}
    vm_id: {type: integer, notnull: true}
    access: {type: bool, default: 0, notnull: true}
    admin: {type: bool, default: 0, notnull: true}
  relations:
    Group: { foreignAlias: GroupVms, local: group_id, foreign: id, onDelete: 'CASCADE' }
    Vm: { foreignAlias: GroupVms, local: vm_id, foreign: id }
    
Group:
  tableName: groups
  columns:
    id: {type: integer, primary: true, autoincrement: true}
    nom: {type: string(15), notnull: true}
    
Steam:
  tableName: serveurs
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    uid: {type: integer, notnull: true}
    idVm: {type: integer, notnull: true}
    port: {type: int(5), notnull: true}
    jeu: {type: integer, notnull: true}
    dir: {type: string(12), notnull: true}
    maxplayers: {type: int(2), notnull: true}
    mm: {type: bool, default: 0, notnull: true}
    amx: {type: bool, default: 0, notnull: true}
    amxx: {type: bool, default: 0, notnull: true}
    mmsrc: {type: bool, default: 0, notnull: true}
    srcm: {type: bool, default: 0, notnull: true}
    es: {type: bool, default: 0, notnull: true}
  relations:
    Vm:
      local: idVm
      foreign: id
      foreignType: one
    Jeu:
      local: jeu
      foreign: id
    Utilisateur:
      local: uid
      foreign: id
      foreignAlias: serveurs

Jeu:
  tableName: jeux
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    nomJeu: {type: string(24), notnull: true}
    installName: {type: string(24), notnull: true}
    launchName: {type: string(24), notnull: true}
    bin:
      type: enum
      values: ['hlds_run', 'srcds_run', 'ucc-bin']
      notnull: true
    source:
      type: bool
      default: 0
      notnull: true
    orangebox:
      type: bool
      default: 0
      notnull: true
    map: {type: string(20), notnull: true}