services:
    voip.listener.query_injector:
        class: DP\VoipServer\VoipServerBundle\EventListener\QueryInjector
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            - { name: doctrine.event_listener, event: postLoad, method: postLoad }
