# This file is part of Dedipanel project
#
# (c) 2010-2014 Dedipanel <http://www.dedicated-panel.net>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    voip.listener.query_injector:
        class: DP\VoipServer\VoipServerBundle\EventListener\QueryInjector
        calls:
            - [ setContainer,[ @service_container ] ]
        tags:
            - { name: doctrine.event_listener, event: postLoad, method: postLoad }
