# (c) 2010-2014 Dedipanel <http://www.dedicated-panel.net>
# 
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

DPGameServerBundle_menu:
    pattern: /menu
    defaults: { _controller: "DPGameServerBundle:Menu:menu" }

DPSteamServerBundle:
    resource: "@DPSteamServerBundle/Resources/config/routing.yml"
    prefix:   /steam/

DPMinecraftBundle:
    resource: "@DPMinecraftServerBundle/Resources/config/routing.yml"
    prefix:   /minecraft/