# (c) 2010-2014 Dedipanel <http://www.dedicated-panel.net>
# 
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    socket.timeout: [1, 0]
    
services:
    socket:
        class: DP\GameServer\GameServerBundle\Service\SocketFactory
        arguments: [ %socket.timeout% ]
    
    packet.factory:
        class: DP\GameServer\GameServerBundle\Service\PacketFactory
    
    game.listener.query_injector:
        class: DP\GameServer\GameServerBundle\Listener\QueryInjector
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: doctrine.event_listener, event: postLoad, method: postLoad }
    
    dedipanel.game.ftp.form.file:
        class: DP\GameServer\GameServerBundle\Form\FTPFileType
        tags:
            - { name: form.type, alias: dedipanel_game_ftp_file }
    
    dedipanel.game.ftp.form.directory:
        class: DP\GameServer\GameServerBundle\Form\FTPDirectoryType
        tags:
            - { name: form.type, alias: dedipanel_game_ftp_directory }
