dedipanel_teamspeak_index:
    pattern: /
    defaults:
        _controller: dedipanel.controller.teamspeak:indexAction
        _sylius:
            paginate: false
            criteria:
                groups: @dedipanel.resolver.user_group:getAccessibleGroupsIdOrEmpty

dedipanel_teamspeak_show:
    pattern: /{id}/show
    defaults:
        _controller: dedipanel.controller.teamspeak:showAction
        _sylius:
            paginate: false

dedipanel_teamspeak_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.teamspeak:createAction
        _sylius:
            form: dedipanel_teamspeak_add

dedipanel_teamspeak_update:
    pattern: /{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: dedipanel.controller.teamspeak:updateAction
        _sylius:
            form: dedipanel_teamspeak_edit

dedipanel_teamspeak_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: dedipanel.controller.teamspeak:deleteAction
        # template: DPTeamspeakServerBundle:TeamspeakServer:delete.html.twig
