dedipanel_teamspeak_instance:
    prefix: /{serverId}/instance
    resource: "@DPTeamspeakServerBundle/Resources/config/routing/instance.yml"

dedipanel_teamspeak_server:
    prefix: /
    resource: "@DPTeamspeakServerBundle/Resources/config/routing/server.yml"
