services:
    dedipanel.teamspeak.form:
        class: DP\VoipServer\TeamspeakServerBundle\Form\TeamspeakServerType
        tags:
            - { name: form.type, alias: dedipanel_teamspeak }

    dedipanel.teamspeak.instance.form:
        class: DP\VoipServer\TeamspeakServerBundle\Form\TeamspeakServerInstanceType
        tags:
            - { name: form.type, alias: dedipanel_teamspeak_instance }
