services:
    dedipanel.teamspeak.form:
        class: DP\VoipServer\TeamspeakServerBundle\Form\TeamspeakServerType
        tags:
            - { name: form.type, alias: dedipanel_teamspeak }

    dedipanel.teamspeak.instance.form:
        class: DP\VoipServer\TeamspeakServerBundle\Form\TeamspeakServerInstanceType
        tags:
            - { name: form.type, alias: dedipanel_teamspeak_instance }

    dedipanel.factory.teamspeak.query:
        class: DP\VoipServer\TeamspeakServerBundle\Service\ServerQueryFactory
        arguments: [ @socket ]
