services:
    app_user.auth.form.type:
        class: DP\Core\UserBundle\Form\Type\ProfileFormType
        arguments: [ %fos_user.model.user.class% ]
        tags:
            - { name: form.type, alias: app_user_profile }
    
    app_user.update_watcher.service:
        class: DP\Core\UserBundle\Service\UpdateWatcherService
        arguments: [0.4]

    app_user.update_watcher.extension:
        class: DP\Core\UserBundle\Extension\UpdateWatcherExtension
        arguments: [@app_user.update_watcher.service]
        tags:
            - { name: twig.extension }
    
    dp_menu.factory:
        class: DP\Core\UserBundle\Menu\Factory\MenuFactory
        arguments: [ "@router" ]
    
    app_user.menu_builder:
        class: DP\Core\UserBundle\Menu\Builder\MenuBuilder
        arguments: [ "@dp_menu.factory" ]
    
    app_user.menu.main:
        class: DP\Core\Menu\MenuItem
        factory_service: app_user.menu_builder
        factory_method: createMainMenu
        arguments: [ "@request" ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }
    
    dp_breadcrumb.items_bag:
        class: DP\Core\UserBundle\Breadcrumb\Bag\BreadcrumbItemsBag
    
    app_user.breadcrumb_builder:
        class: DP\Core\UserBundle\Breadcrumb\Builder\BreadcrumbBuilder
        arguments: [ "@knp_menu.factory" ]
    
    app_user.menu.breadcrumb:
        class: Knp\Menu\MenuItem
        factory_service: app_user.breadcrumb_builder
        factory_method: createBreadcrumb
        arguments: [ "@request", "@dp_breadcrumb.items_bag" ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: breadcrumb}

    dp_breadcrumb.extension:
        class: DP\Core\UserBundle\Extension\BreadcrumbExtension
        arguments: [ "@knp_menu.helper" ]
        tags:
            - { name: twig.extension }
