imports:
    - { resource: services/update.yml }
    - { resource: services/menu.yml }
    - { resource: services/breadcrumb.yml }
    
services:
    dp.repository.user:
        class: DP\Core\UserBundle\Entity\UserRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: [ 'DPCoreUserBundle:User' ]
    
    dp.entity_factory.user:
        class: DP\Core\UserBundle\Entity\Factory\UserFactory
        arguments: [ @fos_user.user_manager ]

    dp.repository.group:
        class: DP\Core\UserBundle\Entity\GroupRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: [ 'DPCoreUserBundle:Group' ]
    
    dp.entity_factory.group:
        class: DP\Core\UserBundle\Entity\Factory\GroupFactory
        arguments: [ @fos_user.group_manager ]
    
    dp.listener.user.registration:
        class: DP\Core\UserBundle\Listener\UserRegistrationListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    
    dp.form.modifier.security_roles:
        class: DP\Core\UserBundle\Form\Modifier\SecurityRolesModifier
        arguments: [ @security.role_hierarchy, %security.role_hierarchy.roles% ]
    
    dp.form.security_roles_type:
        class: DP\Core\UserBundle\Form\Type\SecurityRolesType
        arguments: [ @dp.form.modifier.security_roles, %security.role_hierarchy.roles% ]
        tags:
            - { name: form.type, alias: dp_security_roles }
