imports:
    - { resource: services/form_roles.yml }

services:
    app_user.auth.form.type:
        class: DP\Core\UserBundle\Form\ProfileFormType
        arguments: [ %fos_user.model.user.class% ]
        tags:
            - { name: form.type, alias: app_user_profile }
    
    dedipanel.form.user_admin.add_edit:
        class: DP\Core\UserBundle\Form\UserType
        tags:
            - { name: form.type, alias: dedipanel_user }
    
    dedipanel.user_admin.subscriber:
        class: DP\Core\UserBundle\EventListener\UserAdminListener
        arguments: [ "@fos_user.user_manager" ]
        tags:
            - { name: kernel.event_subscriber }

    dedipanel.group_admin.subscriber:
        class: DP\Core\UserBundle\EventListener\GroupAdminListener
        arguments: [ @security.context ]
        tags:
            - { name: kernel.event_subscriber }
    
    dedipanel.form.group_admin.add_edit:
        class: DP\Core\UserBundle\Form\GroupType
        arguments: [ @security.context ]
        tags:
            - { name: form.type, alias: dedipanel_group }
    
    dedipanel.security.voter.group_assignable_voter:
        class: DP\Core\UserBundle\Voter\GroupAssignableVoter
        arguments: [ @dedipanel.repository.group ]
        public: false
        tags:
            - { name: security.voter, priority: -255 }
    
    dedipanel.kernel.controller.service_args:
        class: DP\Core\UserBundle\EventListener\RoutingServiceArgsListener
        calls: 
            - [ setContainer, [ @service_container ] ]
        tags: 
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    
    dedipanel.resolver.user_group:
        class: DP\Core\UserBundle\Service\UserGroupResolver
        arguments: [ @dedipanel.repository.group, @security.context ]
    
    dedipanel.form.group_assignement.type:
        class: DP\Core\UserBundle\Form\GroupAssignementType
        arguments: [ @dedipanel.resolver.user_group ]
        tags:
            - { name: form.type, alias: dedipanel_group_assignement }
