imports:
    - { resource: services/update.yml }
    - { resource: services/menu.yml }
    - { resource: services/breadcrumb.yml }
    - { resource: services/form_roles.yml }

services:
    app_user.auth.form.type:
        class: DP\Core\UserBundle\Form\Type\ProfileFormType
        arguments: [ %fos_user.model.user.class% ]
        tags:
            - { name: form.type, alias: app_user_profile }
    
    dedipanel.form.user_admin.add_edit:
        class: DP\Core\UserBundle\Form\Type\UserType
        tags:
            - { name: form.type, alias: dedipanel_user }
    
    dedipanel.form.user_admin.edit_roles:
        class: DP\Core\UserBundle\Form\Type\EditRolesType
        tags:
            - { name: form.type, alias: dedipanel_user_update_roles }
    
    dedipanel.user_admin.subscriber:
        class: DP\Core\UserBundle\EventListener\UserAdminListener
        arguments: [ "@fos_user.user_manager" ]
        tags:
            - { name: kernel.event_subscriber }
    
    dedipanel.form.group_admin.add_edit:
        class: DP\Core\UserBundle\Form\Type\GroupType
        tags:
            - { name: form.type, alias: dedipanel_group }
    
    dp.listener.user.registration:
        class: DP\Core\UserBundle\Listener\UserRegistrationListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
