imports:
    - { resource: services/update.yml }
    - { resource: services/menu.yml }
    - { resource: services/breadcrumb.yml }
    - { resource: services/form_roles.yml }

services:
    app_user.auth.form.type:
        class: DP\Core\UserBundle\Form\ProfileFormType
        arguments: [ %fos_user.model.user.class% ]
        tags:
            - { name: form.type, alias: app_user_profile }
    
    dedipanel.form.user_admin.add_edit:
        class: DP\Core\UserBundle\Form\UserType
        tags:
            - { name: form.type, alias: dedipanel_user }
    
    dedipanel.form.user_admin.edit_roles:
        class: DP\Core\UserBundle\Form\EditRolesType
        tags:
            - { name: form.type, alias: dedipanel_user_update_roles }
    
    dedipanel.user_admin.subscriber:
        class: DP\Core\UserBundle\EventListener\UserAdminListener
        arguments: [ "@fos_user.user_manager" ]
        tags:
            - { name: kernel.event_subscriber }
    
    dedipanel.form.group_admin.add_edit:
        class: DP\Core\UserBundle\Form\GroupType
        tags:
            - { name: form.type, alias: dedipanel_group }
    
    dedipanel.security.access.group_voter:
        class: DP\Core\UserBundle\Voter\GroupVoter
        arguments: [ "@logger" ]
        tags:
            - { name: security.voter }
    
    dedipanel.security.listener.admin_security_listener:
        class: DP\Core\UserBundle\EventListener\AdminSecurityListener
        tags:
            - { name: kernel.event_subscriber }
    
    dedipanel.kernel.controller.service_args:
        class: DP\Core\UserBundle\EventListener\RoutingServiceArgsListener
        calls: 
            - [ setContainer, [ @service_container ] ]
        tags: 
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    
    dedipanel.repository.group.nested_tree:
        class: DP\Core\UserBundle\Entity\Repository\GroupRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['DPUserBundle:Group']
